### ISSUE TITLE
Create data ingestor : Country Model

### ISSUE THREAD

**Issue by meomancer** [kartoza/tomorrownow_gap#10]
Child of https://github.com/kartoza/tomorrownow_gap/issues/3

## Problem
We need to create data ingestor for Country model

## Solution
- [ ] Find the country shapefile
- [ ] Create python script extract data from shapefile and safe it to Country Model (with geometry)
- [ ] Script can be run on management command
- [ ] Also as fixtures

**Comment by gubuntu** [comment]
why do we need an ingestor? Country and other vector data sets will be static models that can simply be loaded into PostGIS or stored as GeoJSON files and used from there

**Comment by meomancer** [comment]
This is done
