### ISSUE TITLE
Crop plan generator by FarmGroup

### ISSUE THREAD

**Issue by danangmassandy** [kartoza/tomorrownow_gap#136]
We may to add a new data model for a FarmGroup. A group will have many farms and GAP can send the crop plan report to each different group. There might be a customisation on what fields/columns to be included in the report.

- [x] Add Data model FarmGroup
- [x] Add Data model for FarmGroup Crop Plan fields customisation (to choose which field in the report)
- [x] Generate the crop plan report for each farm group
- [x] Send email to the recipient in each farm group

**Comment by mvmaltitz** [comment]
Brian to confirm the go-ahead for this. 
It will be for the Cara team and consist of about 600 farms

**Comment by danangmassandy** [comment]
For this ticket, we will have two new farms in the new group/category. The detail of the two new farms are sent by Phillip in the email. We will use the farm names as mentioned in the email (not the code like the existing farms). Phillip also sent the email addresses to be added in the recipient of the new farm group.

**Comment by mvmaltitz** [comment]
@meomancer please can you make this ticket a priority
