### ISSUE TITLE
Query via grid pixel instead of per farm

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/tomorrownow_gap#138]
- Phillip will also give us the grid information that we can use to ingest the data from Tomorrow.io API
- Using the grid information, we can tag each group of farmers to the grid, then we query the forecast by the grid. This will reduce the number of query in GAP.

**Comment by mvmaltitz** [comment]
Philip provided 4km grid of Kenya via email

**Comment by danangmassandy** [comment]
I checked the grid data that Philip sent, there are total 36937 grids in Kenya. That means, we need to call the Tomorrow.io API to fetch the short-term forecast with the same number as total grids. Currently, the limit of API Call is only 10k/day (https://github.com/kartoza/tomorrownow_gap/issues/71#issuecomment-2283157003), so we need to ask Tomorrow team to increase the limit. cc: @mvmaltitz
