### ISSUE TITLE
Adjustments to SPW R Code for areas with too much rainfall

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/tomorrownow_gap#156]
Please see email from Philip (Fwd: too wet added to SPW) on 23 Sept 2024 for additional information and zip files. Attachments have also been saved here: https://drive.google.com/drive/folders/1YO5Z4AJszf0JHiCP0RXKR5I7jGiLlOqW

### Adding ‘too wet’ analysis to the SPW model

The attached R code is just the SPW code (no charts etc.)

Code to add to Kartoza SPW to include Too Wet analysis
Line numbers fit the attached R script…

~84-86  Create and set to NA 3 new variables Last4Days, Last2Days, TodayTomorrow
~142 – 154    Here we create and store (in df2) the sum of the Last4Days rainfall, Last2Days, and ForecastTodayTomorrow (NOTE Last4Days is yesterday and previous 3 days – not today)

The ‘Too Wet Report’ then begins around line 348
We take ‘today’ and create a TooWet message – choice of 3 possible.  
	Not too wet to plant
               Likely too wet to plant
               Too wet to plant
These variables and message are written to the output file “LOOKATME” 

User then needs to adapt their message sent to sent the SPW output as long as neither Likely too wet nor Too wet to plant is in the output file for that day.

**Comment by mvmaltitz** [comment]
Email the output to John when it is ready

**Comment by meomancer** [comment]
We put those 4 new columns to csv but still be able to add/remove by the farm group

**Comment by meomancer** [comment]
Could we ask phillip how we name the headers on csv, @mvmaltitz

**Comment by mvmaltitz** [comment]
@meomancer 
Here is the reply from Philip:
We can keep the names as is in the DB but would probably only share the  Too Wet column in the .csv with users.
