### ISSUE TITLE
Error when pulling Windborne data from API

### ISSUE THREAD

**Issue by danangmassandy** [kartoza/tomorrownow_gap#183]
The error that GAP gets is 502 and html response. We can check from this log:

https://tngap.sta.do.kartoza.com/admin/gap/ingestorsession/42/change/?_changelist_filters=ingestor_type__exact%3DWindBorne%2BSystems%2BAPI

**Comment by danangmassandy** [comment]
Looks like it's working today:
https://tngap.sta.do.kartoza.com/admin/gap/ingestorsession/42/change/

![Image](https://github.com/user-attachments/assets/9b0e9111-2af8-4d7f-a726-87e5f3c260a9)

**Comment by danangmassandy** [comment]
We can park this ticket for now, because the error log is gone from Ingestor Session object. The ingestor is now running fine.

**Comment by meomancer** [comment]
To improve this, we need to update how to ingest it
