### ISSUE TITLE
Check that all the datasets are correctly ingested

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/tomorrownow_gap#184]
Check that the following data has been correctly ingested in the staging environment 
- [ ] #8 
- [ ] #9 
- [ ] #137 
- [ ] #165 
- [x] #172

**Comment by danangmassandy** [comment]
I checked on 11 Oct 2024:
| **Ingestor**      | **Status** | **Next Run** |
| ----------------- | ---------- | ------------ |
| CBAM              | OK         | \-           |
| Salient           | OK         | 2024-10-14   |
| Tomorrow.io       | OK         | 2024-10-12   |
| Tahmo CSV         | OK         | \-           |
| Tahmo Disdrometer | OK         | 2024-10-12   |
| Arable            | OK         | 2024-10-12   |
| Windborne         | OK         | 2024-10-12   |
