### ISSUE TITLE
Operationalise in-house models: suitable planting window (SPW R Code)

### ISSUE THREAD

**Issue by danangmassandy** [kartoza/tomorrownow_gap#20]
Check the R code that John has sent.

- [x] Identify the input data
- [x] Check the model output and how to store into GAP
- [x] RnD on R code integration

**Comment by danangmassandy** [comment]
I have checked the R code and tried to integrate the code in the system using Plumber. The required fields are evapotranspirationSum, rainAccumulationSum, LTNPET, and LTNPrecip.

**Comment by danangmassandy** [comment]
The R model is using Tomorrow.io data from below endpoints:
- /historical
- /timelines
- /historical/normals

The variables that R model is using is only: rainAccumulationSum and evapotranspirationSum. I have created a data reader from tomorrow.io but currently it's only limited to these two variable and single point. We may need to add more variable for Crop Plan Generator to fetch short-term forecast.

**Comment by gubuntu** [comment]
SPW must fetch inputs from GAP, not directly from tomorrow.io

and write outputs to DB
