### ISSUE TITLE
Ingest polygon shp bbox

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/tomorrownow_gap#202]
Can we also enhance the BBox to ingest a shape file polygon? It is not urgent, but it would be a valuable feature to include.

**Comment by danangmassandy** [comment]
From discussion in the email:

User needs to call a separate API to upload the shapefile, then use the upload/location ID in the API.
The benefit with this approach are
Upload once, and can be used in many API calls, this reduces the request size
Removing the current POST method that only supports uploading GeoJSON in the request body
We can easily add other supported file formats in the Upload API
GAP will delete the uploaded polygon periodically (like in 2-3 months) to ensure the upload API does not fill up the server storage.
The upload API may send the expiry_date in the response so the user knows about it.
