### ISSUE TITLE
GAP API Swaggers Doc Update

### ISSUE THREAD

**Issue by danangmassandy** [kartoza/tomorrownow_gap#219]
Section orders:

1. User ID
2. Weather & Climate Data
3. Crop Insights Engine

For Weather & Climate Data Parameters

1. Product type (use descriptions if possible, or add the descriptions)

- CBAM Daily Historical Reanalysis (2012 - 2023)
- CBAM Daily Historical Reanalysis (Bias-Corrected) (2012-2023)
- CBAM Short-Term weather forecast (14-days)
- Salient Seasonal weather forecast (3-months)
- Ground Observations (TAHMO stations)
- Radiosonde Observations (Windborne)

2.  Attribute selection based on selected product type
3. Datetime ranges: Start Date, Start Time, End Date, End Time
Need to group multiple request parameters
Adding time parameters are for querying Windborne/Disdrometer #222 

4. File output type
5. Locations: Lat/Lon, Altitude
6. Locations: Bbox or Polygon/LocationID (#202)

**Comment by mvmaltitz** [comment]
@danangmassandy 
![Image](https://github.com/user-attachments/assets/fe93a968-9620-4810-a30e-6cccae43874d)
![Image](https://github.com/user-attachments/assets/ef506a76-336f-41c2-b3b1-460ef7d49c08)

Rename to this:
- Weather & Climate Data (Previously Measurements)
- Crop Insights Engine (Previously Crop plan)

**Comment by mvmaltitz** [comment]
@danangmassandy 

1. I propose to place the product type section first to allow the user to choose the products 

2. Once the product is chosen, the specific attributes linked to that data set should appear in the attributes list below (i.e filter attributes to only show the selected dataset). 

3. We could have a way to show all attributes from all products to allow for a bundle request, but then each attribute needs to be labelled to know which data attributes are chosen. 

![Image](https://github.com/user-attachments/assets/a4b655e6-69d0-44e4-889f-07aad026365e)

![Image](https://github.com/user-attachments/assets/9aec7534-1929-4f0b-9755-469cc97d8080)
