### ISSUE TITLE
[Milestone 2] Create the Crop Plan Generator

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/tomorrownow_gap#26]
- [ ] #20 
- [ ] #27

**Comment by gubuntu** [comment]
you can remove SPW from your second bullet since the first bullet obviates the need to ingest it from TN

**Comment by mvmaltitz** [comment]
**Required for Milestone 2 (phase 1):
-[ ] Ingest farm data
-[ ] Daily email to be sent at 5am
-[ ] SPW R model
-[ ] CSV output
-[ ] Basic Django interface
-[ ] Output includes Plant/Do not Plant & forecast data
-[ ] Data to update daily
-[ ] Custom outputs (future - phase 2)

CC @danangmassandy @meomancer
