### ISSUE TITLE
Stop messages

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/tomorrownow_gap#260]
Hi Michelle 

We can stop the email messages to Regen Org that includes the 92 farmer advisories. The two formal trial site emails to Regen and the direct contacts should however continue.

**Comment by danangmassandy** [comment]
I have removed the users from Regen's farm group recipient list:

![image](https://github.com/user-attachments/assets/d54de88f-8f7a-4917-b85e-1ce2aece9306)
