### ISSUE TITLE
Download all data

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/tomorrownow_gap#266]
e.g All of CBAM for 10 years for all of Kenya

**Comment by danangmassandy** [comment]
I have tested the fix after PR #269 has been deployed to staging. I could download 5 and 10 years CBAM historical data from Kenya bbox, the detail is below:

**5 Years**
start: 2012-01-01
end: 2016-12-31

Time: 2024-11-20 08:09
Total response time: 32.14 s
File size: 2.2 GB
CPU: 0.655
Memory: 1.3 GB


**10 years**
start: 2012-01-01
end: 2021-12-31

Time: 2024-11-20 08:13
Total response time: 90.86 s
File size: 4.5 GB
CPU: 0.85
Memory: 1.57

Between the test, I also cleared the zarr cache on django.

**Comment by danangmassandy** [comment]
how about for other dataset @mvmaltitz? This is the current setting on staging:
![image](https://github.com/user-attachments/assets/b70ec466-4599-4017-816c-1feff166be16)

The dataset that is not in above table will not have any date range restriction.

**Comment by mvmaltitz** [comment]
@danangmassandy From what i understand, the CBAM is most likely to be pulled, but the option needs to be available for all the datasets
