### ISSUE TITLE
Data ingestor: convert CBAM short-term forecast into zarr

### ISSUE THREAD

**Issue by danangmassandy** [kartoza/tomorrownow_gap#48]
For this ticket, it is still pending confirmation:

- Whether we fetch the data from Tomorrow.io API for the whole region, or
- There will be netcdf files like Reanalysis data

If the source is Tomorrow.io API, then we also need a list of variables that we want to fetch.

**Comment by gubuntu** [comment]
you will be fetching now-to-two-week forecasts from the API for the whole area every day and writing to zarr

**Comment by danangmassandy** [comment]
hi @gubuntu, can we overwrite the past forecast data when we fetch the forecast in the next day?
For example, today GAP will fetch data from 07-08-2024 to 15-08-2024, then tomorrow GAP is going to fetch data from 08-08-2024 to 16-08-2024. So, there will be existing forecast data on dates 08-08-2024 until 15-08-2024, this can be overwritten with latest forecast, does this seem correct?

**Comment by gubuntu** [comment]
no don't overwrite. Long-term we definitely need to keep that day's forecast for each day you fetch. But for the meantime Philip requested that we store the full forecast each day

**Comment by danangmassandy** [comment]
- [ ] From GAP Area of Interest, split into smaller area that Tomorrow.io API accepts the request
- [ ] Fetch the forecast data from Tomorrow.io API for each smaller area
- [ ] Store the response into a zarr file
