### ISSUE TITLE
GAP API: add several response format

### ISSUE THREAD

**Issue by danangmassandy** [kartoza/tomorrownow_gap#51]
Currently, the API can return the response in json. We can add another format like:
- NETCDF
- CSV
- GEOJSON
- XML

The current json response might not good when returning data for multiple locations. The sample can be downloaded from [this PR](https://github.com/kartoza/tomorrownow_gap/pull/44). But if we look at the Nasa Power API, their API cannot return json if the query is from regional extent. We could also use the same approach so our json response looks simpler and the response for multiple locations would be in CSV or NETCDF.

**Comment by gubuntu** [comment]
confirm with end-users. I think area responses will need to be in netcdf or a nother coverage or multidimensional format
