### ISSUE TITLE
Create logic to inform the GAP API: ground observations 

### ISSUE THREAD

**Issue by meomancer** [kartoza/tomorrownow_gap#6]
Child of https://github.com/kartoza/tomorrownow_gap/issues/3

## Problem
- [ ] Create API to access ground observation diagram
- [ ] Able to filter also spatial filter

**Comment by mvmaltitz** [comment]
**Source:**
TAHMO Weather Station
Arable Mark 3 weather stations
TN Laser disdrometers

**Measurements:**
Min/max temp, 
Rainfall,
Solar radiation, etc.

Crop Indices:
o NDVI
o Chlorophyll
o Vapor pressure deficit
o Soil moisture %
o Irrigation flow
o GDDs
o Heat stress days
o Frost events
o Sunshine duration
o Irrigation flow
o Pest degree days
o Visual imagery

Extended list of models and insights can be made available
