### ISSUE TITLE
TomorrowNow API Limitation

### ISSUE THREAD

**Issue by meomancer** [kartoza/tomorrownow_gap#71]
# Problem
From example farm, there are around 80 farms
When generate spw, just around farm 40, it gives error

```
["Too Many Calls The request limit for this resource has been reached for the current rate limit window. Wait and retry the operation, or examine your API request volume.", "Too Many Calls The request limit for this resource has been reached for the current rate limit window. Wait and retry the operation, or examine your API request volume."]
```

# Solution
We need to know the limitation of API and also how to fix that

**Comment by meomancer** [comment]
Is the limitation already increased by client?

**Comment by danangmassandy** [comment]
yes, the API request limit has been increased to 10k/day, 5k/hr, 100/s.

**Comment by meomancer** [comment]
We can close this as the current crop plant generator are working fine
