### ISSUE TITLE
Create scheduled tasks for spw generator farm

### ISSUE THREAD

**Issue by meomancer** [kartoza/tomorrownow_gap#74]
- [x] We need to know the schedule of spw generator should be run
       The SPW needs to be generated daily
- [x] Create command to run to all farms
- [x] Autocreate it to celery schedule model

**Comment by danangmassandy** [comment]
I've discussed with the client, the Crop plan generator should be run daily in the morning of East Africa Time.

**Comment by danangmassandy** [comment]
@meomancer I've created a task in PR #85 to generate for all farms and scheduled to run at 23pm UTC (or 2am East Africa Time). But it seems the task is not added to celery schedule model like netcdf-s3-sync. The list below should have generate-crop-plan record.
![image](https://github.com/user-attachments/assets/2375965e-27d5-4811-ac44-3c06b249931d)
