### ISSUE TITLE
Estimate the total storage size required by Zarr files

### ISSUE THREAD

**Issue by danangmassandy** [kartoza/tomorrownow_gap#78]
GAP Data product that will be in zarr:

- CBAM Reanalysis Data
- Salient Seasonal Forecast Data (includes historical forecast)
- Tomorrow.io Short-term Forecast Data (includes historical forecast)

**Comment by danangmassandy** [comment]
For CBAM Reanalysis Data:

- 1 year data = 2.3 GB
- 10 years data = 23 GB

Total time taken to convert 1 year data in staging: ~50minutes.

**Comment by mvmaltitz** [comment]
CBAM zarr 2012-2023 total size: 29GB
Salient zarr 1 forecast_date of 3months data total size: 891MB

**Comment by danangmassandy** [comment]
This is blocked by #139. I need to build a zarr from Tomorrow.io short-term forecast for 1 forecast_date, then I'll be able to estimate the total storage size.
