### ISSUE TITLE
Viamo API Integration

### ISSUE THREAD

**Issue by danangmassandy** [kartoza/tomorrownow_gap#81]
For delivering Crop Plan insight to farmer, we could use Viamo to generate SMS/voice call. The delivery method is still to be confirmed.

https://go.votomobile.org/apidoc/

We should check what information is required for Viamo API.

**Comment by gubuntu** [comment]
Since when are we generating SMSs or voice calls? FFOs are simply going to fetch the crop plans from the GAP API and they will manage how they get sent, not GAP. Or am I missing something?

**Comment by danangmassandy** [comment]
Closing this ticket, this has been confirmed by Brian that we don't need Viamo API integration in v1.
